### ISSUE TITLE
Washington GMUs do not show in Classic 

### ISSUE THREAD

**Issue by FishheadNate** [OpenBounds/OpenHuntingData#371]
The overlay works in NG, but does not display in Classic.
- I check the json file and the geojson link is still valid, but the source link is not working now and I can't find the data on http://geo.wa.gov/ any more.

Do I need to switch this over to have a `shp` source instead of the current `geojson` link?

**Comment by JesseCrocker** [comment]
> Do I need to switch this over to have a shp source instead of the current geojson link?
No, the app doesnt ever read these json files. There is a build process where all the source json files get read, and GeoJSON files get generated, and then vector tiles get generated.
NG reads the vector tiles directly, classic requests raster tiles from the tile rendering server.

The problem here is with the tile rendering server failing to render the tiles, same cause as the issue recently reported with public lands layer not working on the web sometimes, and the reason we havent switched gaiatopo over to the new rendering.
Im hoping to get to fixing this next week.
