### ISSUE TITLE
MN Hunter Walking Trails

### ISSUE THREAD

**Issue by FishheadNate** [OpenBounds/OpenHuntingData#375]
@JesseCrocker Minnesota has walking trails for hunting upland game: https://gisdata.mn.gov/dataset/trans-hunter-walking-trails

Since the trails are saved as polylines, should I add them to OpenBounds or should they go on Gaia Topo?

**Comment by JesseCrocker** [comment]
That data doesnt really fit with OpenHuntingData, at least the way we have it setup now. All the styles are setup for rendering polygons, so this data wont render properly.

Currently GaiaTopo is not really setup for importing small datasets like this, it's something we could discuss doing in the future, but it's probably something we would not want to do, because the imported trails would not be available for routing, and we would get more bug reports about "why doesnt routing work on this trail".

This dataset is relatively small, and looks like it could probably be imported into OpenStreetMap. That's the only way i can see making use of this data. Importing the data would take a couple hours of work converting the data to OSM format, a couple hours of work to propose the import, a couple hours of work spread over a month interacting with the OSM community on the proposed import, then 1-2 days of work to do the importing.
